name: Node.js CI

on: push

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Instalando as dependências
      run: npm install
    
    - name: Executando os testes unitários
      run: npm run test
